CREATE TABLE LPUSER(
	USER_EMAIL VARCHAR2(50) NOT NULL,
	USER_PASSWORD VARCHAR2(100),
	USER_NICKNAME VARCHAR2(30) NOT NULL,
	USER_AUTH CHAR(1),
	USER_DELFLAG CHAR(1) DEFAULT 'F',
	USER_EMAILCHK CHAR(1) DEFAULT 'N',
	USER_EMAILKEY VARCHAR2(300),
	USER_ISWRITE CHAR(1) DEFAULT 'T' NOT NULL,
	PRIMARY KEY(USER_EMAIL)
);

 -- 스케치북 테이블 -- 
CREATE TABLE LPSKETCHBOOK(
	SKETCH_ID VARCHAR2(20),
	USER_EMAIL VARCHAR2(50),
	SKETCH_TITLE VARCHAR2(100),
	SKETCH_THEME VARCHAR2(20),
	SKETCH_SHARE CHAR(1) DEFAULT 'F',
	SKETCH_BLOCK CHAR(1) DEFAULT 'F',
	SKETCH_SPATH VARCHAR2(100),
	PRIMARY KEY(SKETCH_ID)
);
-- 스케치북 시퀀스 --
CREATE SEQUENCE LPSKETCHBOOK_SEQ START WITH 1 INCREMENT BY 1;

 -- 스크랩 , 좋아요 테이블 --
CREATE TABLE LPCOLLECT(
	COL_ID VARCHAR2(20) NOT NULL,
	USER_EMAIL VARCHAR2(50) NOT NULL,
	SKETCH_ID VARCHAR2(20) NOT NULL,
	COL_SCRAPE CHAR(1) DEFAULT 'F'  NOT NULL,
	COL_LIKE CHAR(1) DEFAULT 'F'  NOT NULL,
	PRIMARY KEY(COL_ID),
	FOREIGN KEY (SKETCH_ID) REFERENCES LPSKETCHBOOK(SKETCH_ID) ON DELETE CASCADE
);
-- 스크랩 , 좋아요 시퀀스 --
CREATE SEQUENCE LPCOLLECT_SEQ START WITH 1 INCREMENT BY 1;

 -- 캔버스 테이블 --
CREATE TABLE LPCANVAS(
	CAN_ID VARCHAR2(20) NOT NULL, 
	SKETCH_ID VARCHAR2(20) NOT NULL, 
	CAN_TITLE VARCHAR2(100),	
	CAN_TYPE NUMBER, 
	CAN_PAGENO NUMBER NOT NULL,
	PRIMARY KEY(CAN_ID),
	FOREIGN KEY (SKETCH_ID) REFERENCES LPSKETCHBOOK(SKETCH_ID) ON DELETE CASCADE
);
-- 캔버스 시퀀스 --
CREATE SEQUENCE LPCANVAS_SEQ START WITH 1 INCREMENT BY 1;

 --자유 캔버스 테이블
CREATE TABLE LPTEXT(
	TEXT_ID VARCHAR2(20) NOT NULL, --SEQ
	CAN_ID VARCHAR2(20) NOT NULL,
	TEXT_CONTENT VARCHAR2(4000), --html 태그가 그대로 들어감
	TEXT_NO NUMBER NOT NULL, --템플릿내 컨텐츠 삽입 영역별 부여된 번호
	IMG_SPATH VARCHAR2(100), --이미지 서버 경로
	PRIMARY KEY(TEXT_ID),
	FOREIGN KEY (CAN_ID) REFERENCES LPCANVAS(CAN_ID) ON DELETE CASCADE
);

 -- 자유 캔버스 시퀀스
CREATE SEQUENCE LPTEXT_SEQ START WITH 1 INCREMENT BY 1;

 -- 일정 테이블 --
CREATE TABLE LPDAYS(
	DAYS_ID VARCHAR2(20) NOT NULL,
	CAN_ID VARCHAR2(20) NOT NULL,
	DAYS_TITLE VARCHAR2(100),
	DAYS_CONTENT VARCHAR2(200),
	DAYS_SDATE DATE,
	DAYS_EDATE DATE,
	DAYS_X NUMBER,
	DAYS_Y NUMBER,
	DAYS_ADDRESS VARCHAR2(200),
	PRIMARY KEY(DAYS_ID),
	FOREIGN KEY (CAN_ID) REFERENCES LPCANVAS(CAN_ID) ON DELETE CASCADE
);

 -- 일정 캔버스 시퀀스
CREATE SEQUENCE LPDAYS_SEQ START WITH 1 INCREMENT BY 1;

 -- 관광지/음식점/숙소 테이블 생성
CREATE TABLE LPMAPDATA(
	MAP_ID VARCHAR2(20) NOT NULL,
	MAP_X NUMBER,
	MAP_Y NUMBER,
	MAP_TYPE VARCHAR2(10),
	MAP_TITLE VARCHAR2(200),
	MAP_CONTENT VARCHAR2(500),
	PRIMARY KEY(MAP_ID)	
);

 -- 관광지/음식점/숙소 시퀀스
CREATE SEQUENCE LPMAPDATA_SEQ START WITH 1 INCREMENT BY 1;

 -- 채팅 사용자 테이블 생성
CREATE TABLE LPCHATLIST(
	USER_NICKNAME VARCHAR2(50) NOT NULL,
	PRIMARY KEY(USER_NICKNAME)
);

 CREATE TABLE LPCHATROOM(
	CHR_ID VARCHAR2(20) NOT NULL,
	CHR_SENDER VARCHAR2(50) NOT NULL,
	CHR_RECEIVER VARCHAR2(50),
	CHR_SOUT CHAR(1) DEFAULT 'F' NOT NULL,
	CHR_ROUT CHAR(1) DEFAULT 'F' NOT NULL,	
	PRIMARY KEY(CHR_ID)
);

 -- 채팅방 시퀀스 생성
CREATE SEQUENCE LPCHATROOM_SEQ START WITH 1 INCREMENT BY 1;

 -- 채팅방 내용 테이블 -- 
CREATE TABLE LPCHATCONTENT(
	CHC_ID VARCHAR2(20) NOT NULL,
	CHR_ID VARCHAR2(20) NOT NULL,
	USER_NICKNAME VARCHAR2(20),
	CHC_MESSAGE VARCHAR2(1000),
	CHC_OUT CHAR(1) DEFAULT 'F' NOT NULL,
	CHC_REGDATE DATE,
	PRIMARY KEY(CHC_ID)
);

 CREATE SEQUENCE LPCHATCONTENT_SEQ START WITH 1 INCREMENT BY 1;

 CREATE TABLE LPCHATIMAGE(
	CHI_ID VARCHAR2(20) NOT NULL,
	CHR_ID VARCHAR2(20) NOT NULL,
	CHI_RPATH VARCHAR2(500) NOT NULL,
	CHI_SPATH VARCHAR2(500) NOT NULL,	
	PRIMARY KEY(CHI_ID)
);

 CREATE SEQUENCE LPCHATIMAGE_SEQ START WITH 1 INCREMENT BY 1;
 
 -- 시퀀스 반환 함수 생성
CREATE FUNCTION GET_CONTENT_SEQ RETURN NUMBER IS
BEGIN RETURN LPCHATCONTENT_SEQ.NEXTVAL; END;