-- 유저 삭제
DROP TABLE LPUSER;
-- 자유 캔버스 삭제
DROP TABLE LPTEXT;
-- 일정 캔버스 삭제
DROP TABLE LPDAYS;
-- 캔버스 삭제
DROP TABLE LPCANVAS;
-- 스크랩,좋아요 삭제
DROP TABLE LPCOLLECT;
-- 스케치북 삭제
DROP TABLE LPSKETCHBOOK;
-- 맵 데이터 삭제
DROP TABLE LPMAPDATA;
-- 채팅 파일 삭제
DROP TABLE LPCHATIMAGE;
-- 채팅 내용 삭제
DROP TABLE LPCHATCONTENT;
-- 채팅방 삭제
DROP TABLE LPCHATROOM;
-- 채팅 리스트 삭제
DROP TABLE LPCHATLIST;

-- 시퀀스 삭제
DROP SEQUENCE LPSKETCHBOOK_SEQ;
DROP SEQUENCE LPCOLLECT_SEQ;
DROP SEQUENCE LPCANVAS_SEQ;
DROP SEQUENCE LPTEXT_SEQ;
DROP SEQUENCE LPDAYS_SEQ;
DROP SEQUENCE LPMAPDATA_SEQ;
DROP SEQUENCE LPCHATROOM_SEQ;
DROP SEQUENCE LPCHATCONTENT_SEQ;
DROP SEQUENCE LPCHATIMAGE_SEQ;