-- My sketchbook test data
-- With me
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user1@email.com', 'alone01', 'With me', 'Y', './img/alone/01.jpg', 'F');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user1@email.com', 'alone02', 'With me', 'Y', './img/alone/02.jpg', 'F');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user1@email.com', 'alone03', 'With me', 'Y', './img/alone/03.jpg', 'F');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user1@email.com', 'alone04', 'With me', 'Y', './img/alone/04.jpg', 'F');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user1@email.com', 'alone05', 'With me', 'Y', './img/alone/05.jpg', 'F');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user1@email.com', 'alone06', 'With me', 'Y', './img/alone/06.jpg', 'F');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user1@email.com', 'alone07', 'With me', 'Y', './img/alone/07.jpg', 'F');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user1@email.com', 'alone08', 'With me', 'Y', './img/alone/08.jpg', 'F');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user1@email.com', 'alone09', 'With me', 'Y', './img/alone/09.jpg', 'F');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user1@email.com', 'alone10', 'With me', 'Y', './img/alone/10.jpg', 'F');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user1@email.com', 'alone11', 'With me', 'Y', './img/alone/11.jpg', 'F');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user1@email.com', 'alone12', 'With me', 'Y', './img/alone/12.jpg', 'F');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user1@email.com', 'alone13', 'With me', 'Y', './img/alone/13.jpg', 'F');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user1@email.com', 'alone14', 'With me', 'Y', './img/alone/14.jpg', 'F');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user1@email.com', 'alone15', 'With me', 'Y', './img/alone/15.jpg', 'F');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user1@email.com', 'alone16', 'With me', 'Y', './img/alone/16.jpg', 'F');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user1@email.com', 'alone17', 'With me', 'Y', './img/alone/17.jpg', 'F');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user1@email.com', 'alone18', 'With me', 'Y', './img/alone/18.jpg', 'F');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user1@email.com', 'alone19', 'With me', 'Y', './img/alone/19.jpg', 'F');

-- With family
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user1@email.com', 'family01', 'With family', 'Y', './img/family/01.jpg', 'F');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user1@email.com', 'family02', 'With family', 'Y', './img/family/02.jpg', 'F');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user1@email.com', 'family03', 'With family', 'Y', './img/family/03.jpg', 'F');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user1@email.com', 'family04', 'With family', 'Y', './img/family/04.jpg', 'F');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user1@email.com', 'family05', 'With family', 'Y', './img/family/05.jpg', 'F');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user1@email.com', 'family06', 'With family', 'Y', './img/family/06.jpg', 'F');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user1@email.com', 'family07', 'With family', 'Y', './img/family/07.jpg', 'F');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user1@email.com', 'family08', 'With family', 'Y', './img/family/08.jpg', 'F');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user1@email.com', 'family09', 'With family', 'Y', './img/family/09.jpg', 'F');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user1@email.com', 'family10', 'With family', 'Y', './img/family/10.jpg', 'F');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user1@email.com', 'family11', 'With family', 'Y', './img/family/11.jpg', 'F');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user1@email.com', 'family12', 'With family', 'Y', './img/family/12.jpg', 'F');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user1@email.com', 'family13', 'With family', 'Y', './img/family/13.jpg', 'F');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user1@email.com', 'family14', 'With family', 'Y', './img/family/14.jpg', 'F');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user1@email.com', 'family15', 'With family', 'Y', './img/family/15.jpg', 'F');

-- With friend
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user2@email.com', 'friend01', 'With friend', 'Y', './img/friend/01.jpg', 'F');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user2@email.com', 'friend02', 'With friend', 'Y', './img/friend/02.jpg', 'F');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user2@email.com', 'friend03', 'With friend', 'Y', './img/friend/03.jpg', 'F');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user2@email.com', 'friend04', 'With friend', 'Y', './img/friend/04.jpg', 'F');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user2@email.com', 'friend05', 'With friend', 'Y', './img/friend/05.jpg', 'F');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user2@email.com', 'friend06', 'With friend', 'Y', './img/friend/06.jpg', 'F');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user2@email.com', 'friend07', 'With friend', 'Y', './img/friend/07.jpg', 'F');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user2@email.com', 'friend08', 'With friend', 'Y', './img/friend/08.jpg', 'F');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user2@email.com', 'friend09', 'With friend', 'Y', './img/friend/09.jpg', 'F');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user2@email.com', 'friend10', 'With friend', 'Y', './img/friend/10.jpg', 'F');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user2@email.com', 'friend11', 'With friend', 'Y', './img/friend/11.jpg', 'F');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user2@email.com', 'friend12', 'With friend', 'Y', './img/friend/12.jpg', 'F');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user2@email.com', 'friend13', 'With friend', 'Y', './img/friend/13.jpg', 'F');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user2@email.com', 'friend14', 'With friend', 'Y', './img/friend/14.jpg', 'F');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user2@email.com', 'friend15', 'With friend', 'Y', './img/friend/15.jpg', 'F');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user2@email.com', 'friend16', 'With friend', 'Y', './img/friend/16.jpg', 'F');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user2@email.com', 'friend17', 'With friend', 'Y', './img/friend/17.jpg', 'F');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user2@email.com', 'friend18', 'With friend', 'Y', './img/friend/18.jpg', 'F');
                                                                                                                                                                 
-- With love                                                                                                                                                     
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user2@email.com', 'couple01', 'With love', 'Y', './img/couple/01.jpg', 'F');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user2@email.com', 'couple02', 'With love', 'Y', './img/couple/02.jpg', 'F');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user2@email.com', 'couple03', 'With love', 'Y', './img/couple/03.jpg', 'F');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user2@email.com', 'couple04', 'With love', 'Y', './img/couple/04.jpg', 'F');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user2@email.com', 'couple05', 'With love', 'Y', './img/couple/05.jpg', 'F');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user2@email.com', 'couple06', 'With love', 'Y', './img/couple/06.jpg', 'F');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user2@email.com', 'couple07', 'With love', 'Y', './img/couple/07.jpg', 'F');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user2@email.com', 'couple08', 'With love', 'Y', './img/couple/08.jpg', 'F');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user2@email.com', 'couple09', 'With love', 'Y', './img/couple/09.jpg', 'F');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user2@email.com', 'couple10', 'With love', 'Y', './img/couple/10.jpg', 'F');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user2@email.com', 'couple11', 'With love', 'Y', './img/couple/11.jpg', 'F');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user2@email.com', 'couple12', 'With love', 'Y', './img/couple/12.jpg', 'F');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user2@email.com', 'couple13', 'With love', 'Y', './img/couple/13.jpg', 'F');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user2@email.com', 'couple14', 'With love', 'Y', './img/couple/14.jpg', 'F');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user2@email.com', 'couple15', 'With love', 'Y', './img/couple/15.jpg', 'F');

-- Scrap
INSERT INTO HAPPY.LPCOLLECT (COL_ID, USER_EMAIL, SKETCH_ID, COL_SCRAPE, COL_LIKE) VALUES(LPCOLLECT_SEQ.NEXTVAL, 'user2@email.com', '1', 'T', 'T');
INSERT INTO HAPPY.LPCOLLECT (COL_ID, USER_EMAIL, SKETCH_ID, COL_SCRAPE, COL_LIKE) VALUES(LPCOLLECT_SEQ.NEXTVAL, 'user2@email.com', '2', 'T', 'T');
INSERT INTO HAPPY.LPCOLLECT (COL_ID, USER_EMAIL, SKETCH_ID, COL_SCRAPE, COL_LIKE) VALUES(LPCOLLECT_SEQ.NEXTVAL, 'user2@email.com', '3', 'T', 'T');
INSERT INTO HAPPY.LPCOLLECT (COL_ID, USER_EMAIL, SKETCH_ID, COL_SCRAPE, COL_LIKE) VALUES(LPCOLLECT_SEQ.NEXTVAL, 'user2@email.com', '4', 'T', 'T');
INSERT INTO HAPPY.LPCOLLECT (COL_ID, USER_EMAIL, SKETCH_ID, COL_SCRAPE, COL_LIKE) VALUES(LPCOLLECT_SEQ.NEXTVAL, 'user2@email.com', '5', 'T', 'T');
INSERT INTO HAPPY.LPCOLLECT (COL_ID, USER_EMAIL, SKETCH_ID, COL_SCRAPE, COL_LIKE) VALUES(LPCOLLECT_SEQ.NEXTVAL, 'user2@email.com', '6', 'T', 'T');
INSERT INTO HAPPY.LPCOLLECT (COL_ID, USER_EMAIL, SKETCH_ID, COL_SCRAPE, COL_LIKE) VALUES(LPCOLLECT_SEQ.NEXTVAL, 'user2@email.com', '7', 'T', 'T');
INSERT INTO HAPPY.LPCOLLECT (COL_ID, USER_EMAIL, SKETCH_ID, COL_SCRAPE, COL_LIKE) VALUES(LPCOLLECT_SEQ.NEXTVAL, 'user2@email.com', '8', 'T', 'T');
INSERT INTO HAPPY.LPCOLLECT (COL_ID, USER_EMAIL, SKETCH_ID, COL_SCRAPE, COL_LIKE) VALUES(LPCOLLECT_SEQ.NEXTVAL, 'user2@email.com', '9', 'T', 'T');
INSERT INTO HAPPY.LPCOLLECT (COL_ID, USER_EMAIL, SKETCH_ID, COL_SCRAPE, COL_LIKE) VALUES(LPCOLLECT_SEQ.NEXTVAL, 'user2@email.com', '10', 'T', 'T');
INSERT INTO HAPPY.LPCOLLECT (COL_ID, USER_EMAIL, SKETCH_ID, COL_SCRAPE, COL_LIKE) VALUES(LPCOLLECT_SEQ.NEXTVAL, 'user2@email.com', '11', 'T', 'T');
INSERT INTO HAPPY.LPCOLLECT (COL_ID, USER_EMAIL, SKETCH_ID, COL_SCRAPE, COL_LIKE) VALUES(LPCOLLECT_SEQ.NEXTVAL, 'user2@email.com', '12', 'T', 'T');
INSERT INTO HAPPY.LPCOLLECT (COL_ID, USER_EMAIL, SKETCH_ID, COL_SCRAPE, COL_LIKE) VALUES(LPCOLLECT_SEQ.NEXTVAL, 'user2@email.com', '13', 'T', 'T');
INSERT INTO HAPPY.LPCOLLECT (COL_ID, USER_EMAIL, SKETCH_ID, COL_SCRAPE, COL_LIKE) VALUES(LPCOLLECT_SEQ.NEXTVAL, 'user2@email.com', '14', 'T', 'T');
INSERT INTO HAPPY.LPCOLLECT (COL_ID, USER_EMAIL, SKETCH_ID, COL_SCRAPE, COL_LIKE) VALUES(LPCOLLECT_SEQ.NEXTVAL, 'user2@email.com', '15', 'T', 'T');
INSERT INTO HAPPY.LPCOLLECT (COL_ID, USER_EMAIL, SKETCH_ID, COL_SCRAPE, COL_LIKE) VALUES(LPCOLLECT_SEQ.NEXTVAL, 'user2@email.com', '16', 'T', 'T');
INSERT INTO HAPPY.LPCOLLECT (COL_ID, USER_EMAIL, SKETCH_ID, COL_SCRAPE, COL_LIKE) VALUES(LPCOLLECT_SEQ.NEXTVAL, 'user2@email.com', '17', 'T', 'T');
INSERT INTO HAPPY.LPCOLLECT (COL_ID, USER_EMAIL, SKETCH_ID, COL_SCRAPE, COL_LIKE) VALUES(LPCOLLECT_SEQ.NEXTVAL, 'user2@email.com', '18', 'T', 'T');
INSERT INTO HAPPY.LPCOLLECT (COL_ID, USER_EMAIL, SKETCH_ID, COL_SCRAPE, COL_LIKE) VALUES(LPCOLLECT_SEQ.NEXTVAL, 'user2@email.com', '20', 'T', 'T');
INSERT INTO HAPPY.LPCOLLECT (COL_ID, USER_EMAIL, SKETCH_ID, COL_SCRAPE, COL_LIKE) VALUES(LPCOLLECT_SEQ.NEXTVAL, 'user2@email.com', '21', 'T', 'T');
INSERT INTO HAPPY.LPCOLLECT (COL_ID, USER_EMAIL, SKETCH_ID, COL_SCRAPE, COL_LIKE) VALUES(LPCOLLECT_SEQ.NEXTVAL, 'user2@email.com', '22', 'T', 'T');
INSERT INTO HAPPY.LPCOLLECT (COL_ID, USER_EMAIL, SKETCH_ID, COL_SCRAPE, COL_LIKE) VALUES(LPCOLLECT_SEQ.NEXTVAL, 'user2@email.com', '23', 'T', 'T');
INSERT INTO HAPPY.LPCOLLECT (COL_ID, USER_EMAIL, SKETCH_ID, COL_SCRAPE, COL_LIKE) VALUES(LPCOLLECT_SEQ.NEXTVAL, 'user2@email.com', '24', 'T', 'T');
INSERT INTO HAPPY.LPCOLLECT (COL_ID, USER_EMAIL, SKETCH_ID, COL_SCRAPE, COL_LIKE) VALUES(LPCOLLECT_SEQ.NEXTVAL, 'user2@email.com', '25', 'T', 'T');
INSERT INTO HAPPY.LPCOLLECT (COL_ID, USER_EMAIL, SKETCH_ID, COL_SCRAPE, COL_LIKE) VALUES(LPCOLLECT_SEQ.NEXTVAL, 'user2@email.com', '26', 'T', 'T');
INSERT INTO HAPPY.LPCOLLECT (COL_ID, USER_EMAIL, SKETCH_ID, COL_SCRAPE, COL_LIKE) VALUES(LPCOLLECT_SEQ.NEXTVAL, 'user2@email.com', '27', 'T', 'T');
INSERT INTO HAPPY.LPCOLLECT (COL_ID, USER_EMAIL, SKETCH_ID, COL_SCRAPE, COL_LIKE) VALUES(LPCOLLECT_SEQ.NEXTVAL, 'user2@email.com', '28', 'T', 'T');
INSERT INTO HAPPY.LPCOLLECT (COL_ID, USER_EMAIL, SKETCH_ID, COL_SCRAPE, COL_LIKE) VALUES(LPCOLLECT_SEQ.NEXTVAL, 'user2@email.com', '29', 'T', 'T');
INSERT INTO HAPPY.LPCOLLECT (COL_ID, USER_EMAIL, SKETCH_ID, COL_SCRAPE, COL_LIKE) VALUES(LPCOLLECT_SEQ.NEXTVAL, 'user2@email.com', '30', 'T', 'T');

INSERT INTO HAPPY.LPCOLLECT (COL_ID, USER_EMAIL, SKETCH_ID, COL_SCRAPE, COL_LIKE) VALUES(LPCOLLECT_SEQ.NEXTVAL, 'user3@email.com', '1', 'T', 'T');
INSERT INTO HAPPY.LPCOLLECT (COL_ID, USER_EMAIL, SKETCH_ID, COL_SCRAPE, COL_LIKE) VALUES(LPCOLLECT_SEQ.NEXTVAL, 'user3@email.com', '2', 'T', 'T');
INSERT INTO HAPPY.LPCOLLECT (COL_ID, USER_EMAIL, SKETCH_ID, COL_SCRAPE, COL_LIKE) VALUES(LPCOLLECT_SEQ.NEXTVAL, 'user3@email.com', '3', 'T', 'T');
INSERT INTO HAPPY.LPCOLLECT (COL_ID, USER_EMAIL, SKETCH_ID, COL_SCRAPE, COL_LIKE) VALUES(LPCOLLECT_SEQ.NEXTVAL, 'user3@email.com', '4', 'T', 'T');
INSERT INTO HAPPY.LPCOLLECT (COL_ID, USER_EMAIL, SKETCH_ID, COL_SCRAPE, COL_LIKE) VALUES(LPCOLLECT_SEQ.NEXTVAL, 'user3@email.com', '5', 'T', 'T');
INSERT INTO HAPPY.LPCOLLECT (COL_ID, USER_EMAIL, SKETCH_ID, COL_SCRAPE, COL_LIKE) VALUES(LPCOLLECT_SEQ.NEXTVAL, 'user3@email.com', '6', 'T', 'T');
INSERT INTO HAPPY.LPCOLLECT (COL_ID, USER_EMAIL, SKETCH_ID, COL_SCRAPE, COL_LIKE) VALUES(LPCOLLECT_SEQ.NEXTVAL, 'user3@email.com', '7', 'T', 'T');
INSERT INTO HAPPY.LPCOLLECT (COL_ID, USER_EMAIL, SKETCH_ID, COL_SCRAPE, COL_LIKE) VALUES(LPCOLLECT_SEQ.NEXTVAL, 'user3@email.com', '8', 'T', 'T');
INSERT INTO HAPPY.LPCOLLECT (COL_ID, USER_EMAIL, SKETCH_ID, COL_SCRAPE, COL_LIKE) VALUES(LPCOLLECT_SEQ.NEXTVAL, 'user3@email.com', '9', 'T', 'T');
INSERT INTO HAPPY.LPCOLLECT (COL_ID, USER_EMAIL, SKETCH_ID, COL_SCRAPE, COL_LIKE) VALUES(LPCOLLECT_SEQ.NEXTVAL, 'user3@email.com', '10', 'T', 'T');

