SELECT COUNT(USER_EMAIL) USER_EMAIL FROM LPUSER WHERE USER_EMAIL = 'test@test.com'


SELECT * FROM LPUSER;


SELECT USER_EMAIL, USER_PASSWORD, USER_NICKNAME, USER_AUTH, USER_EMAILCHK
	FROM LPUSER
		WHERE LOWER(USER_EMAIL) = LOWER('test@dd.com') AND USER_AUTH = 'U'  AND USER_DELFLAG ='F' 