CREATE TABLE LPDAYS(
	DAYS_ID VARCHAR2(20) NOT NULL,
	CAN_ID VARCHAR2(20) NOT NULL,
	DAYS_TITLE VARCHAR2(100),
	DAYS_CONTENT VARCHAR2(200),
	DAYS_SDATE DATE,
	DAYS_EDATE DATE,
	DAYS_X NUMBER,
	DAYS_Y NUMBER,
	DAYS_ADDRESS VARCHAR2(200),
	PRIMARY KEY(DAYS_ID),
	FOREIGN KEY (CAN_ID) REFERENCES LPCANVAS(CAN_ID) ON DELETE CASCADE
);

 -- 일정 캔버스 시퀀스
CREATE SEQUENCE LPDAYS_SEQ START WITH 1 INCREMENT BY 1;

 --자유 캔버스 테이블
CREATE TABLE LPTEXT(
	TEXT_ID VARCHAR2(20) NOT NULL, --SEQ
	CAN_ID VARCHAR2(20) NOT NULL,
	TEXT_CONTENT VARCHAR2(4000), --html 태그가 그대로 들어감
	TEXT_NO NUMBER NOT NULL, --템플릿내 컨텐츠 삽입 영역별 부여된 번호
	IMG_SPATH VARCHAR2(100), --이미지 서버 경로
	PRIMARY KEY(TEXT_ID),
	FOREIGN KEY (CAN_ID) REFERENCES LPCANVAS(CAN_ID) ON DELETE CASCADE
);

 -- 자유 캔버스 시퀀스
CREATE SEQUENCE LPTEXT_SEQ START WITH 1 INCREMENT BY 1;