-- 스케치북 관련 쿼리

-- 스케치북 테이블 생성
CREATE TABLE LPSKETCHBOOK(
	SKETCH_ID	VARCHAR2(20),
	USER_EMAIL	VARCHAR2(50),
	SKETCH_TITLE	VARCHAR2(50),
	SKETCH_THEME	VARCHAR2(20),
	SKETCH_SHARE	CHAR(1),
	SKETCH_BLOCK 	CHAR(1),
	SKETCH_SPATH	VARCHAR2(100),
);


-- 유저 테이블 생성
CREATE TABLE LPUSER(
	USER_EMAIL VARCHAR2(50) NOT NULL,
	USER_PASSWORD VARCHAR2(100) NOT NULL,
	USER_NICKNAME VARCHAR2(20) NOT NULL,
	USER_AUTH CHAR(1),
	USER_DELFLAG CHAR(1) DEFAULT 'F',
	USER_EMAILCHK CHAR(1),
	USER_EMAILKEY VARCHAR2(300),
	USER_ISWRITE CHAR(1) DEFAULT 'T'
);


-- 좋아요 및 스크랩 테이블 생성
CREATE TABLE LPCOLLECT(
	COL_ID	VARCHAR2(20),
	USER_EMAIL	VARCHAR2(50),
	SKETCH_ID	VARCHAR2(20),
	COL_SCRAPE	CHAR(1),
	COL_LIKE	CHAR(1)
);


-- 캔버스 테이블 생성
CREATE TABLE LPCANVAS(
	CAN_ID VARCHAR2(20),
	SKETCH_ID VARCHAR2(20),
	CAN_TITLE VARCHAR2(50),
	CAN_CONTENT VARCHAR2(200),
	CAN_TYPE NUMBER,
	CAN_PAGENO NUMBER
);


-- 일정 테이블 생성
CREATE TABLE LPDAYS(
	DAYS_ID VARCHAR2(20),
	CAN_ID  VARCHAR2(20),
	DAYS_TITLE VARCHAR2(50),
	DAYS_CONTENT VARCHAR2(200),
	DAYS_SDATE DATE,
	DAYS_EDATE DATE,
	DAYS_X NUMBER,
	DAYS_Y NUMBER,
	DAYS_ADDRESS VARCHAR2(100)
);


--자유 캔버스 테이블 생성
CREATE TABLE LPTEXT(
	TEXT_ID VARCHAR2(20), --SEQ
	CAN_ID VARCHAR2(20),
	TEXT_CONTENT VARCHAR2(200), --html 태그가 그대로 들어감
	TEXT_NO NUMBER, --템플릿내 컨텐츠 삽입 영역별 부여된 번호
	IMG_SPATH VARCHAR2(100) --이미지 서버 경로
);


CREATE SEQUENCE LPSKETCHBOOK_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE LPCOLLECT_SEQ START WITH 1 INCREMENT BY 1;


-- 스케치북 다중 완전 삭제를 위한 PRIMARY KEY 제약 조건 설정
ALTER TABLE LPSKETCHBOOK ADD CONSTRAINT LPSKETCHBOOK_PK PRIMARY KEY(SKETCH_ID);
ALTER TABLE LPCANVAS ADD CONSTRAINT LPCANVAS_PK PRIMARY KEY(CAN_ID);


-- 스케치북 다중 완전 삭제를 위한 FOREIGN KEY 제약 조건 설정
ALTER TABLE LPCOLLECT ADD CONSTRAINT LPCOLLECT_FK2 FOREIGN KEY (SKETCH_ID) REFERENCES LPSKETCHBOOK(SKETCH_ID) ON DELETE CASCADE;
ALTER TABLE LPCANVAS ADD CONSTRAINT LPCANVAS_FK FOREIGN KEY(SKETCH_ID) REFERENCES LPSKETCHBOOK(SKETCH_ID)  ON DELETE CASCADE;


-- 스케치북 다중 완전 삭제를 위한 FOREIGN KEY CASCADE 제약 조건 설정
ALTER TABLE LPTEXT ADD CONSTRAINT LPTEXT_FK FOREIGN KEY(CAN_ID) REFERENCES LPCANVAS(CAN_ID) ON DELETE CASCADE;
ALTER TABLE LPDAYS ADD CONSTRAINT LPDAYS_FK FOREIGN KEY(CAN_ID) REFERENCES LPCANVAS(CAN_ID) ON DELETE CASCADE;




-- 스케치북 작성 

	
	-- 스케치북 작성 권한 확인
	SELECT USER_ISWRITE FROM LPUSER WHERE USER_EMAIL = '128@happy.com';
	
	-- 스케치북  생성  입력 
	INSERT INTO LPSKETCHBOOK
		(SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME,
		SKETCH_SHARE, SKETCH_DELFLAG, SKETCH_SPATH, SKETCH_BLOCK)
	VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, '130@happy.com','여행타이틀', '나홀로', 'Y', 'F', 'c:\abc\dedf', 'F');




-- 스케치북 수정

	-- 스케치북 정보 수정  (사용자-마이페이지)
	UPDATE LPSKETCHBOOK SET SKETCH_TITLE='제목~!@!#@@#', SKETCH_THEME='가족여행', SKETCH_SHARE='Y', SKETCH_SPATH='c:\abbb\cccc' 
		WHERE USER_EMAIL='124@happy.com' AND SKETCH_ID='0001';
			               
	
	-- 스케치북 스크랩 상태 가져오기
	SELECT COL_SCRAPE FROM LPCOLLECT WHERE USER_EMAIL='128@happy.com' AND SKETCH_ID='0006';
	
	-- 스케치북 스크랩 수정(취소, 삭제)
	UPDATE LPCOLLECT SET COL_SCRAPE='F' WHERE USER_EMAIL='128@happy.com' AND SKETCH_ID='0006';
 
 	
	-- 스케치북 '좋아요' 상태 가져오기
	SELECT COL_LIKE FROM LPCOLLECT WHERE USER_EMAIL='128@happy.com' AND SKETCH_ID='0006';	
	
	-- 스케치북 '좋아요'(취소, 삭제)
	UPDATE LPCOLLECT SET COL_LIKE='F' WHERE USER_EMAIL='128@happy.com' AND SKETCH_ID='0008';


-- 스케치북 조회
	
	-- 좋아요가 가장 높은 순서 3개로  조회
	SELECT MAXLIKE, SKETCH_ID, SKETCH_THEME, SKETCH_TITLE, SKETCH_SPATH 
		FROM (SELECT COUNT(*) MAXLIKE, LPCOLLECT.SKETCH_ID, LPSKETCHBOOK.SKETCH_THEME, LPSKETCHBOOK.SKETCH_TITLE, LPSKETCHBOOK.SKETCH_SPATH
			FROM LPSKETCHBOOK, LPCOLLECT
			WHERE COL_LIKE='T' AND LPCOLLECT.SKETCH_ID=LPSKETCHBOOK.SKETCH_ID AND SKETCH_THEME='나홀로' AND SKETCH_SHARE='Y' AND SKETCH_BLOCK='F' GROUP BY LPCOLLECT.SKETCH_ID, LPSKETCHBOOK.SKETCH_THEME, LPSKETCHBOOK.SKETCH_TITLE, LPSKETCHBOOK.SKETCH_SPATH ORDER BY MAXLIKE DESC, SKETCH_ID DESC)
		WHERE ROWNUM BETWEEN 1 AND 3;


	-- 스케치북 테마별 조회 무한스크롤 3*2	
	  SELECT SKETCH_ID, SKETCH_TITLE, SKETCH_SPATH
		 FROM (SELECT ROWNUM RNUM, SKETCH_ID, SKETCH_TITLE, SKETCH_SPATH
			FROM (SELECT SKETCH_ID, SKETCH_TITLE, SKETCH_SPATH 
				FROM LPSKETCHBOOK
				WHERE SKETCH_THEME='나홀로' AND SKETCH_SHARE='Y' AND SKETCH_BLOCK='F' 
				ORDER BY SKETCH_ID DESC)
				)
			WHERE RNUM BETWEEN 1 AND 6;
		
	 	
	-- 스케치북 좋아요 카운트 조회	
	SELECT COUNT(*) CNT 
		FROM LPCOLLECT WHERE SKETCH_ID='0006' AND COL_LIKE='T';
	
		
	-- 작성자 닉네임 조회
	SELECT LPUSER.USER_NICKNAME FROM LPSKETCHBOOK, LPUSER
		WHERE LPSKETCHBOOK.USER_EMAIL = LPUSER.USER_EMAIL AND SKETCH_ID ='0030';
	
	
	-- 자신이 작성한 스케치북 조회(사용자-마이페이지)
	SELECT SKETCH_ID, SKETCH_THEME, SKETCH_TITLE, SKETCH_SPATH, SKETCH_SHARE, SKETCH_BLOCK
		FROM (SELECT ROWNUM RNUM, SKETCH_ID, SKETCH_THEME, SKETCH_TITLE, SKETCH_SPATH, SKETCH_SHARE, SKETCH_BLOCK
			FROM (SELECT SKETCH_ID, SKETCH_THEME, SKETCH_TITLE, SKETCH_SPATH, SKETCH_SHARE, SKETCH_BLOCK
					FROM LPSKETCHBOOK 
					WHERE USER_EMAIL='124@happy.com'
					ORDER BY SKETCH_ID DESC)
				)
				WHERE RNUM BETWEEN 1 AND 9;
	
	-- 스케치북 좋아요 카운트 조회	
	SELECT COUNT(*) CNT 
		FROM LPCOLLECT WHERE SKETCH_ID= '' AND COL_LIKE='T'; 
	
	
	-- 작성자 닉네임 조회
	SELECT LPUSER.USER_NICKNAME FROM LPSKETCHBOOK, LPUSER
		WHERE LPSKETCHBOOK.USER_EMAIL = LPUSER.USER_EMAIL AND SKETCH_ID ='0030';
	
		
	-- 작성 스케치북 상세조회(사용자- 마이페이지 정보 수정을 위한 상세 조회)
	SELECT SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SPATH, SKETCH_SHARE 
		FROM LPSKETCHBOOK WHERE USER_EMAIL=#{user_email} AND SKETCH_ID=#{sketch_id}	
		
		
	-- 스크랩한 스케치북 조회
	SELECT SKETCH_ID, SKETCH_THEME, SKETCH_TITLE, SKETCH_SPATH	
		FROM (SELECT ROWNUM RNUM, SKETCH_ID, SKETCH_THEME, SKETCH_TITLE, SKETCH_SPATH
			FROM (SELECT LPSKETCHBOOK.SKETCH_ID, SKETCH_THEME, SKETCH_TITLE, SKETCH_SPATH FROM LPSKETCHBOOK, LPCOLLECT 
					WHERE LPCOLLECT.USER_EMAIL='128@happy.com' 
					AND LPSKETCHBOOK.SKETCH_ID = LPCOLLECT.SKETCH_ID AND  LPCOLLECT.COL_SCRAPE = 'T' AND LPSKETCHBOOK.SKETCH_SHARE='Y' AND LPSKETCHBOOK.SKETCH_BLOCK='F'
					ORDER BY SKETCH_ID DESC)
			)
			WHERE RNUM BETWEEN 1 AND 9;
		;
 
	
	-- 스크랩한 스케치북 갯수 조회
	SELECT COUNT(*) CNT FROM LPCOLLECT WHERE USER_EMAIL='128@happy.com' AND COL_SCRAPE='T';
	
	-- 스케치북 좋아요 카운트 조회
	SELECT COUNT(*) CNT FROM LPCOLLECT  WHERE SKETCH_ID='0006' AND COL_LIKE = 'T';
	

	-- 작성자 닉네임 조회
	SELECT LPUSER.USER_NICKNAME FROM LPSKETCHBOOK, LPUSER
		WHERE LPSKETCHBOOK.USER_EMAIL = LPUSER.USER_EMAIL AND SKETCH_ID ='0030';


-- 스케치북 삭제 
	

	-- 선택한 스케치북 스크랩 다중 취소
	UPDATE LPCOLLECT SET COL_SCRAPE='F' WHERE USER_EMAIL IN ('128@happy.com') AND SKETCH_ID IN('0006', '0007', '0004'); 

	-- 선택한 스케치북 다중 완전 삭제
	DELETE FROM LPSKETCHBOOK WHERE SKETCH_ID IN ('0026');


-- 스케치북 스크랩 등록		
	
	-- 최초 등록
	INSERT INTO LPCOLLECT(COL_ID, USER_EMAIL, SKETCH_ID, COL_SCRAPE , COL_LIKE)
		SELECT LPCOLLECT_SEQ.NEXTVAL,'128@happy.com', '0006', 'F', 'F' FROM DUAL WHERE NOT EXISTS(SELECT * FROM LPCOLLECT WHERE USER_EMAIL='128@happy.com' AND SKETCH_ID ='0006');
	
		
	-- 스케치북 스크랩 등록, 상태 변경
	UPDATE LPCOLLECT SET COL_SCRAPE='T' WHERE USER_EMAIL='128@happy.com' AND SKETCH_ID='0006'; 
	  		

-- 스케치북 '좋아요' 등록
	
	-- 최초 등록
	INSERT INTO LPCOLLECT(COL_ID, USER_EMAIL, SKETCH_ID, COL_SCRAPE , COL_LIKE)
		SELECT LPCOLLECT_SEQ.NEXTVAL,'128@happy.com', '0006', 'F', 'F' FROM DUAL WHERE NOT EXISTS(SELECT * FROM LPCOLLECT WHERE USER_EMAIL='128@happy.com' AND SKETCH_ID ='0006');

	
	-- 좋아요 상태 변경
	UPDATE LPCOLLECT SET COL_LIKE='T' WHERE USER_EMAIL='128@happy.com' AND SKETCH_ID='0006';











