-- 사용자  =====================================================
-- 테이블 재생성을 위해 테이블을 DROP하는 쿼리
DROP TABLE LPUSER;

-- 회원 테이블 생성
CREATE TABLE LPUSER(
	USER_EMAIL VARCHAR2(50) NOT NULL,
	USER_PASSWORD VARCHAR2(100) NOT NULL,
	USER_NICKNAME VARCHAR2(20) NOT NULL,
	USER_AUTH CHAR(1),
	USER_DELFLAG CHAR(1) DEFAULT 'F',
	USER_EMAILCHK CHAR(1) DEFAULT 'N',
	USER_EMAILKEY VARCHAR2(300),
	USER_ISWRITE CHAR(1) DEFAULT 'T'
);

-- 스케치북  ====================================================
-- 테이블 재생성을 위해 테이블을 DROP하는 쿼리
DROP TABLE LPSKETCHBOOK;
DROP TABLE LPCOLLECT;

-- 스케치북 테이블 생성
CREATE TABLE LPSKETCHBOOK(
	SKETCH_ID	VARCHAR2(20),
	USER_EMAIL	VARCHAR2(50),
	SKETCH_TITLE	VARCHAR2(50),
	SKETCH_THEME	VARCHAR2(20),
	SKETCH_SHARE	CHAR(1),
	SKETCH_DELFLAG	CHAR(1),
	SKETCH_CONTENT	VARCHAR2(200),
	SKETCH_SPATH	VARCHAR2(100),
	SKETCH_BLOCK CHAR(1)
);

-- 스크랩 테이블 생성
CREATE TABLE LPCOLLECT(
	COL_ID	VARCHAR2(20),
	USER_EMAIL	VARCHAR2(50),
	SKETCH_ID	VARCHAR2(20),
	COL_SCRAPE	CHAR(1),
	COL_LIKE	CHAR(1)
);

CREATE SEQUENCE LPSKETCHBOOK_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE LPCOLLECT_SEQ START WITH 1 INCREMENT BY 1;

-- 캔버스 ====================================================================
-- 테이블 재생성을 위해 테이블을 DROP하는 쿼리
DROP TABLE LPCANVAS;
DROP TABLE LPMAPDATA;
DROP TABLE LPDAYS;
DROP TABLE LPTEXT;

-- 시퀀스 재생성을 위해 시퀀스를 DROP하는 쿼리
DROP SEQUENCE LPCANVAS_SEQ;
DROP SEQUENCE LPMAPDATA_SEQ;
DROP SEQUENCE LPTEXT_SEQ;
DROP SEQUENCE LPDAYS_SEQ;

-- 캔버스 테이블 생성
CREATE TABLE LPCANVAS(
	CAN_ID VARCHAR2(20), --SEQ
	SKETCH_ID VARCHAR2(20), 
	CAN_TITLE VARCHAR2(50),
	CAN_CONTENT VARCHAR2(200),
	CAN_TYPE NUMBER, --템플릿  종류에 따른 번호
	CAN_PAGENO NUMBER
);

-- 관광지/음식점/숙소 테이블 생성
CREATE TABLE LPMAPDATA(
	MAP_ID VARCHAR2(20),
	MAP_X  NUMBER,
	MAP_Y  NUMBER,
	MAP_TYPE VARCHAR2(10),
	MAP_TITLE VARCHAR2(50),
	MAP_CONTENT VARCHAR2(200)
);

-- 일정 테이블
CREATE TABLE LPDAYS(
	DAYS_ID VARCHAR2(20),
	CAN_ID  VARCHAR2(20),
	DAYS_TITLE VARCHAR2(50),
	DAYS_CONTENT VARCHAR2(200),
	DAYS_SDATE DATE,
	DAYS_EDATE DATE,
	DAYS_X NUMBER,
	DAYS_Y NUMBER,
	DAYS_ADDRESS VARCHAR2(100)
);

--자유 캔버스 테이블
CREATE TABLE LPTEXT(
	TEXT_ID VARCHAR2(20), --SEQ
	CAN_ID VARCHAR2(20),
	TEXT_CONTENT VARCHAR2(200), --html 태그가 그대로 들어감
	TEXT_NO NUMBER, --템플릿내 컨텐츠 삽입 영역별 부여된 번호
	IMG_SPATH VARCHAR2(100) --이미지 서버 경로
);

-- 캔버스 시퀀스
CREATE SEQUENCE LPCANVAS_SEQ START WITH 1 INCREMENT BY 1;
-- 관광지/음식점/숙소 시퀀스
CREATE SEQUENCE LPMAPDATA_SEQ START WITH 1 INCREMENT BY 1;
-- 자유 캔버스 시퀀스
CREATE SEQUENCE LPTEXT_SEQ START WITH 1 INCREMENT BY 1;
-- 일정 캔버스 시퀀스
CREATE SEQUENCE LPDAYS_SEQ START WITH 1 INCREMENT BY 1;

-- 채팅 ====================================================================		
-- 테이블 재생성을 위해 테이블을 DROP하는 쿼리
DROP TABLE LPCHATLIST;
DROP TABLE LPCHATROOM;
DROP TABLE LPCHATIMAGE;

-- 시퀀스 재생성을 위해 시퀀스를 DROP하는 쿼리
DROP SEQUENCE LPCHATROOM_SEQ;
DROP SEQUENCE LPCHATIMAGE_SEQ;

-- 테이블 생성
CREATE TABLE LPCHATLIST(
	USER_NICKNAME VARCHAR2(20)
);

CREATE TABLE LPCHATROOM(
	CHR_ID VARCHAR2(20),
	CHR_SENDER VARCHAR2(20),
	CHR_RECEIVER VARCHAR2(50),
	CHR_SOUT CHAR(1),
	CHR_ROUT CHAR(1),
	CHR_CONTENT VARCHAR2(2000),
	CHR_REGDATE DATE
);

CREATE TABLE LPCHATIMAGE(
	CHI_ID VARCHAR2(20),
	CHI_RPATH VARCHAR2(200),
	CHI_SPATH VARCHAR2(200),
	FILE_SIZE NUMBER
);

-- 테이블 시퀀스 생성
CREATE SEQUENCE LPCHATROOM_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE LPCHATIMAGE_SEQ START WITH 1 INCREMENT BY 1;