-- 사용자 테이블 =====================================================
-- 테이블 재생성을 위해 테이블을 DROP하는 쿼리
DROP TABLE LPUSER;

-- 테이블 생성
CREATE TABLE LPUSER(
	USER_EMAIL VARCHAR2(50) NOT NULL,
	USER_PASSWORD VARCHAR2(100) NOT NULL,
	USER_NICKNAME VARCHAR2(20) NOT NULL,
	USER_AUTH CHAR(1),
	USER_DELFLAG CHAR(1) DEFAULT 'F',
	USER_EMAILCHK CHAR(1),
	USER_EMAILKEY VARCHAR2(300),
	USER_ISWRITE CHAR(1) DEFAULT 'T'
);

-- 스케치북 테이블 ====================================================
-- 테이블 재생성을 위해 테이블을 DROP하는 쿼리
DROP TABLE LPSKETCHBOOK;
DROP TABLE LPCOLLECT;

-- 테이블 생성
CREATE TABLE LPSKETCHBOOK(
	SKETCH_ID	VARCHAR2(20),
	USER_EMAIL	VARCHAR2(50),
	SKETCH_TITLE	VARCHAR2(50),
	SKETCH_THEME	VARCHAR2(20),
	SKETCH_SHARE	CHAR(1),
	SKETCH_DELFLAG	CHAR(1),
	SKETCH_CONTENT	VARCHAR2(200),
	SKETCH_RPATH	VARCHAR2(100),
);

CREATE TABLE LPCOLLECT(
	COL_ID	VARCHAR2(20),
	USER_EMAIL	VARCHAR2(50),
	SKETCH_ID	VARCHAR2(20),
	COL_SCRAPE	CHAR(1),
	COL_LIKE	CHAR(1)
);

-- 채팅 ==========================================================================================================================================			
-- 테이블 재생성을 위해 테이블을 DROP하는 쿼리
DROP TABLE LPCHATLIST;
DROP TABLE LPCHATROOM;
DROP TABLE LPCHATIMAGE;

-- 시퀀스 재생성을 위해 시퀀스를 DROP하는 쿼리
DROP SEQUENCE LPCHATROOM_SEQ;
DROP SEQUENCE LPCHATIMAGE_SEQ;

-- 테이블 생성
CREATE TABLE LPCHATLIST(
	USER_NICKNAME VARCHAR2(20)
);

CREATE TABLE LPCHATROOM(
	CHR_ID VARCHAR2(20),
	CHR_SENDER VARCHAR2(20),
	CHR_RECEIVER VARCHAR2(50),
	CHR_SOUT CHAR(1),
	CHR_ROUT CHAR(1),
	CHR_CONTENT VARCHAR2(2000),
	CHR_REGDATE DATE
);

CREATE TABLE LPCHATIMAGE(
	CHI_ID VARCHAR2(20),
	CHI_RPATH VARCHAR2(200),
	CHI_SPATH VARCHAR2(200),
	FILE_SIZE NUMBER
);

-- 테이블 시퀀스 생성
CREATE SEQUENCE LPCHATROOM_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE LPCHATIMAGE_SEQ START WITH 1 INCREMENT BY 1;