--LPUSER 이메일 인증 및 권한 변경
UPDATE LPUSER SET USER_EMAILCHK = 'Y' WHERE USER_EMAIL = 'user1@email.com';
UPDATE LPUSER SET USER_EMAILCHK = 'Y' WHERE USER_EMAIL = 'user2@email.com';
UPDATE LPUSER SET USER_EMAILCHK = 'Y' WHERE USER_EMAIL = 'admin@email.com';
UPDATE LPUSER SET USER_AUTH = 'M' WHERE USER_EMAIL = 'admin@email.com';

-- My sketchbook test data
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user1@email.com', 'title01', '나홀로', 'Y', './img/test/01.jpg', 'F');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user1@email.com', 'title02', '가족여행', 'Y', './img/test/02.jpg', 'F');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user1@email.com', 'title03', '연인과함께', 'Y', './img/test/03.jpg', 'F');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user1@email.com', 'title04', '친구와함께', 'Y', './img/test/04.jpg', 'F');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user1@email.com', 'title05', '나홀로', 'Y', './img/test/05.jpg', 'T');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user1@email.com', 'title06', '가족여행', 'Y', './img/test/06.jpg', 'T');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user1@email.com', 'title07', '연인과함께', 'Y', './img/test/07.jpg', 'T');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user1@email.com', 'title08', '친구와함께', 'Y', './img/test/08.jpg', 'T');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user1@email.com', 'title09', '나홀로', 'Y', './img/test/09.jpg', 'F');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user1@email.com', 'title10', '가족여행', 'Y', './img/test/10.jpg', 'F');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user1@email.com', 'title11', '연인과함께', 'Y', './img/test/11.jpg', 'F');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user1@email.com', 'title12', '친구와함께', 'Y', './img/test/12.jpg', 'F');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user1@email.com', 'title13', '나홀로', 'Y', './img/test/13.jpg', 'T');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user1@email.com', 'title14', '가족여행', 'Y', './img/test/14.jpg', 'T');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user1@email.com', 'title15', '연인과함께', 'Y', './img/test/15.jpg', 'T');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user1@email.com', 'title16', '친구와함께', 'Y', './img/test/16.jpg', 'T');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user1@email.com', 'title17', '나홀로', 'N', './img/test/17.jpg', 'F');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user1@email.com', 'title18', '가족여행', 'N', './img/test/18.jpg', 'F');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user1@email.com', 'title19', '연인과함께', 'N', './img/test/19.jpg', 'F');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user1@email.com', 'title20', '친구와함께', 'N', './img/test/20.jpg', 'F');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user1@email.com', 'title21', '나홀로', 'N', './img/test/21.jpg', 'F');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user1@email.com', 'title22', '가족여행', 'N', './img/test/22.jpg', 'F');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user1@email.com', 'title23', '연인과함께', 'N', './img/test/23.jpg', 'F');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user1@email.com', 'title24', '친구와함께', 'N', './img/test/24.jpg', 'F');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user1@email.com', 'title25', '나홀로', 'N', './img/test/25.jpg', 'F');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user1@email.com', 'title26', '가족여행', 'N', './img/test/26.jpg', 'F');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user1@email.com', 'title27', '연인과함께', 'N', './img/test/27.jpg', 'F');
INSERT INTO HAPPY.LPSKETCHBOOK (SKETCH_ID, USER_EMAIL, SKETCH_TITLE, SKETCH_THEME, SKETCH_SHARE, SKETCH_SPATH, SKETCH_BLOCK) VALUES(LPSKETCHBOOK_SEQ.NEXTVAL, 'user1@email.com', 'title28', '친구와함께', 'N', './img/test/28.jpg', 'F');


INSERT INTO HAPPY.LPCOLLECT (COL_ID, USER_EMAIL, SKETCH_ID, COL_SCRAPE, COL_LIKE) VALUES(LPCOLLECT_SEQ.NEXTVAL, '1@naver.com', '1', 'T', 'T');
INSERT INTO HAPPY.LPCOLLECT (COL_ID, USER_EMAIL, SKETCH_ID, COL_SCRAPE, COL_LIKE) VALUES(LPCOLLECT_SEQ.NEXTVAL, '2@naver.com', '2', 'T', 'T');
INSERT INTO HAPPY.LPCOLLECT (COL_ID, USER_EMAIL, SKETCH_ID, COL_SCRAPE, COL_LIKE) VALUES(LPCOLLECT_SEQ.NEXTVAL, '3@naver.com', '3', 'T', 'T');
INSERT INTO HAPPY.LPCOLLECT (COL_ID, USER_EMAIL, SKETCH_ID, COL_SCRAPE, COL_LIKE) VALUES(LPCOLLECT_SEQ.NEXTVAL, '4@naver.com', '4', 'T', 'T');
INSERT INTO HAPPY.LPCOLLECT (COL_ID, USER_EMAIL, SKETCH_ID, COL_SCRAPE, COL_LIKE) VALUES(LPCOLLECT_SEQ.NEXTVAL, '5@naver.com', '5', 'T', 'T');
INSERT INTO HAPPY.LPCOLLECT (COL_ID, USER_EMAIL, SKETCH_ID, COL_SCRAPE, COL_LIKE) VALUES(LPCOLLECT_SEQ.NEXTVAL, '6@naver.com', '5', 'T', 'T');
INSERT INTO HAPPY.LPCOLLECT (COL_ID, USER_EMAIL, SKETCH_ID, COL_SCRAPE, COL_LIKE) VALUES(LPCOLLECT_SEQ.NEXTVAL, '7@naver.com', '6', 'T', 'T');
INSERT INTO HAPPY.LPCOLLECT (COL_ID, USER_EMAIL, SKETCH_ID, COL_SCRAPE, COL_LIKE) VALUES(LPCOLLECT_SEQ.NEXTVAL, '8@naver.com', '7', 'T', 'T');
INSERT INTO HAPPY.LPCOLLECT (COL_ID, USER_EMAIL, SKETCH_ID, COL_SCRAPE, COL_LIKE) VALUES(LPCOLLECT_SEQ.NEXTVAL, '9@naver.com', '8', 'T', 'T');




