--LPUSER 이메일 인증 및 권한 변경
UPDATE LPUSER SET USER_EMAILCHK = 'Y' WHERE USER_EMAIL = 'user1@email.com';
UPDATE LPUSER SET USER_EMAILCHK = 'Y' WHERE USER_EMAIL = 'user2@email.com';
UPDATE LPUSER SET USER_EMAILCHK = 'Y' WHERE USER_EMAIL = 'admin@email.com';
UPDATE LPUSER SET USER_AUTH = 'M' WHERE USER_EMAIL = 'admin@email.com';